language: csharp
solution: CSharpHTTPClient/CSharpHTTPClient.sln
env:
  matrix:
    secure: KJrQ+NfmzlgCSXRyqeAMDGZUG6GO4/+xk1T0wGy1BgVz8seo/fDWL8osWEljB4Sj05sfFj7CM+rociwL6sdVyqCiHbCAM7XuHs58D+4Tlh5pGHL+G1qOl65/pDl0ulq+M7PwDxHPZ60/oyH2a16t5jtD9e4W31y2fXzEbHGLHXg=
script:
  - make test
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./CSharpHTTPClient/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    branch: master
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) 
